Grasso
ITSRizzoli/2021-23.SA.UFS07 pull request #13
Opened 2022-04-29 10:20 UTC by Rvbino

quello che volete

2022-04-30 18:27 UTC, alessandro-aglietti requested changes
- [x] levare spazio

2022-04-30 18:27 UTC, alessandro-aglietti commented on .github/workflows/github-actions-demo.yml
> +jobs:
levare spazio

2022-05-03 08:50 UTC, alessandro-aglietti approved these changes

2022-05-03 08:52 UTC, alessandro-aglietti approved these changes

2022-05-05 16:00 UTC, alessandro-aglietti requested changes
mancano tutti i file del progetto vanilla!!

2022-05-05 16:00 UTC, alessandro-aglietti commented on .github/workflows/github-actions-demo.yml
> +            nvm use
manca `npm install` e `npm run build`

2022-05-10 10:54 UTC, alessandro-aglietti approved these changes

2022-05-28 23:57 UTC, aaglietti-itsrizzoli commented
@Rvbino gentilmente riapri la pr perche' github si e' incastrato su "unresolved convertions" grazie

2022-05-28 23:57 UTC, closed without merging