Lucchini
ITSRizzoli/2021-23.SA.UFS07 pull request #16
Opened 2022-04-29 10:20 UTC by ivanluc2002

cognome

2022-04-30 18:30 UTC, alessandro-aglietti approved these changes

2022-04-30 18:34 UTC, alessandro-aglietti commented
test

2022-04-30 18:35 UTC, alessandro-aglietti approved these changes

2022-04-30 18:39 UTC, alessandro-aglietti approved these changes

2022-04-30 18:42 UTC, alessandro-aglietti approved these changes

2022-05-03 12:35 UTC, alessandro-aglietti requested changes
@ivanluc2002 non hai ignorato la dist!!!!!

2022-05-07 09:06 UTC, alessandro-aglietti requested changes

2022-05-07 09:06 UTC, alessandro-aglietti commented on Progettofrontendvanilla/dist/index.html
> +<!doctype html><html><head><meta charset="utf-8"/></head><body><h1 onclick="onClickAlert();">Click me to show a date!!!</h1><div></div><script src="main.min.js"></script></body></html>
questo file e tutti gli altri della dist non ci devono stare!

2022-05-07 09:06 UTC, alessandro-aglietti commented on Progettofrontendvanilla/.gitignore
> +node_modules
manca dist da ignorare

2022-05-10 08:10 UTC, aaglietti-itsrizzoli approved these changes

2022-05-10 10:49 UTC, alessandro-aglietti approved these changes

2022-05-10 10:49 UTC, alessandro-aglietti approved these changes

2022-05-10 23:45 UTC, alessandro-aglietti commented
@ivanluc2002 non ti preoccupare per 

![image](https://user-images.githubusercontent.com/638619/167742153-56692726-a8ca-4bc8-90db-2c084182a746.png)

e' un bug di GitHub mi sa :D

- https://stackoverflow.com/questions/71946575/after-rebase-and-force-push-unresolved-conversations-remain-outdated-and-block
- https://twitter.com/BenRCongdon/status/1456113928249827331

2022-05-28 23:56 UTC, aaglietti-itsrizzoli commented
@ivanluc2002 gentilmente riapri la PR perche' github si e' incastrato su "unresolved conversations" grazie

2022-05-28 23:56 UTC, closed without merging