Stefani
ITSRizzoli/2021-23.SA.UFS07 pull request #22
Opened 2022-04-29 10:21 UTC by MarcoTheBest123

quello che volete

2022-04-30 22:16 UTC, alessandro-aglietti approved these changes

2022-05-05 15:05 UTC, alessandro-aglietti requested changes
@MarcoTheBest123  non hai messo nel gitignore la dist e la node_modules!!!

2022-05-10 10:50 UTC, alessandro-aglietti approved these changes

2022-05-28 23:55 UTC, aaglietti-itsrizzoli commented
@MarcoTheBest123 gentilmente riapri la pr perche' github si e' incastrato su "unresolved conversations" grazie

2022-05-28 23:55 UTC, closed without merging