RobertHanu
ITSRizzoli/2021-23.SA.UFS07 pull request #25
Opened 2022-04-29 10:23 UTC by BassDrake

fix

2022-04-30 19:04 UTC, alessandro-aglietti approved these changes

2022-05-05 15:53 UTC, alessandro-aglietti requested changes

2022-05-05 15:53 UTC, alessandro-aglietti commented on progetto-frontend-vanilla/.gitignore
> +node_modules
manca cartella dist da ignorare

2022-05-05 15:53 UTC, alessandro-aglietti commented on progetto-frontend-vanilla/dist/index.html
> +<!doctype html><html><head><meta charset="utf-8"/></head><body><h1 onclick="onClickAlert();">Click me to show a date!!!</h1><div><img src="img/sun.png"/></div><script src="main.min.js"></script></bod
questo file va ignorato, non deve essere versionato

2022-05-10 10:29 UTC, alessandro-aglietti approved these changes

2022-05-28 23:53 UTC, aaglietti-itsrizzoli commented
@BassDrake ti chiedo un favore, riapri la PR perche' github si e' incastrato su "Unresolved conversations". Grazie

2022-05-28 23:53 UTC, closed without merging