Marcandalli
ITSRizzoli/2021-23.SA.UFS07 pull request #29
Opened 2022-04-29 10:24 UTC by Marcaaa92

Simone marcandalli pull request

2022-04-29 16:48 UTC, alessandro-aglietti requested changes
@Marcaaa92 le commit non seguono le regole di convetional commits, con rebase interactive fai reword!

2022-04-30 19:06 UTC, alessandro-aglietti approved these changes

2022-05-03 08:23 UTC, aaglietti-itsrizzoli approved these changes

2022-05-05 15:49 UTC, alessandro-aglietti requested changes
mancano tutti i file del pro-getto

2022-05-05 15:49 UTC, alessandro-aglietti commented on .github/workflows/github-actions-demo.yml
> +          nvm use
manca `npm install` e `npm run build`

2022-05-07 08:46 UTC, alessandro-aglietti approved these changes

2022-05-10 13:32 UTC, alessandro-aglietti commented
@Marcaaa92 ricordati di fare rebase e poi aggiungere le modifiche che abbiamo fatto oggi (puoi ispirarti alle PR degli altri)

2022-05-13 14:51 UTC, aaglietti-itsrizzoli commented
we @Marcaaa92 prova a seguire le slide da 97 a 102 per aggiungere il deploy automatico su surge e anche ispirandoti alle pr dei compagni di classe eventualmente fatti aiutare da qualcuno!

2023-05-26 12:36 UTC, closed without merging