HanuC
ITSRizzoli/2021-23.SA.UFS07 pull request #31
Opened 2022-04-29 10:28 UTC by hCri02

2022-04-29 17:02 UTC, alessandro-aglietti requested changes
- [ ] convetional commits da sistemare
- [ ] EOF da sistemare

2022-04-29 17:02 UTC, alessandro-aglietti commented on .github/workflows/github-actions-demo.yml
> +      - run: exit 1
@hCri02 manca linea vuota in fondo al fine

2022-05-03 08:42 UTC, aaglietti-itsrizzoli approved these changes

2022-05-03 08:43 UTC, alessandro-aglietti approved these changes

2022-05-05 15:43 UTC, alessandro-aglietti approved these changes

2022-05-05 15:46 UTC, alessandro-aglietti requested changes
mancano tutti i file del progetto vanilla di esempio visti a lezione

2022-05-05 15:46 UTC, alessandro-aglietti commented on .github/workflows/github-actions-demo.yml
> +          npm install
manca `npm run build`

2022-05-05 15:46 UTC, alessandro-aglietti commented on progetto-frontend-vanilla/package.json
> +  "license": "ISC"
mancano le dipendenze webpack

2022-05-07 08:42 UTC, aaglietti-itsrizzoli approved these changes

2022-05-07 08:43 UTC, alessandro-aglietti approved these changes

2023-08-01 10:30 UTC, closed without merging